- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove old HTML Content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Download frontend content and extract it
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/frontend/archive/main.zip"
    dest: /tmp
    remote_src: yes
